#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Tøxic 
# Email      » johntezali56@gmail.com
# telegram   » https://t.me/ToxicSavage
# whatsapp   » wa.me/+254716637803
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Toxic Savage

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

clear
clear

echo -e ""
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}  ${BGWHITE}                MENU MANAGER BOT                ${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo -e " ${NC}   ${NC}[${GREEN}01${NC}]${YELL} Menu BOT Panel${NC}"
echo -e " ${NC}   ${NC}[${GREEN}02${NC}]${YELL} Menu BOT Notifikasi${NC}"
echo -e " ${NC}   ${NC}[${GREEN}03${NC}]${YELL} Menu BOT Backup${NC}"
echo -e " ${NC}   ${NC}[${BRED}0X${NC}]${BRED} Exit Menu BOT${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e ""
read -p "  Select From Options [ 1-3 / 0X ] »» " menu

case $menu in
1 | 01) clear ; mbot-panel ;;
2 | 02) clear ; bot ;;
3 | 03) clear ; 
echo -e "  Note: "
echo -e "  Before using a backup bot"
echo -e "  Please Setup Your ID & BOT Token !"
sleep 2
mbot-backup ;;
0 | X | 0X)
    clear
    menu
    ;;    
*)
    m-bot
    ;;
esac