#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Tøxic 
# Email      » johntezali56@gmail.com
# telegram   » https://t.me/ToxicSavage
# whatsapp   » wa.me/+254716637803
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Toxic Savage

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

clear
clear

clear
echo -e ""
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}  ${BGWHITE}               EXSTRA MENU MANAGER              ${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo -e " ${NC}   ${NC}[${GREEN}01${NC}]${YELL} Change ssh banners${NC}"
echo -e " ${NC}   ${NC}[${GREEN}02${NC}]${YELL} Change Domain${NC}"
echo -e " ${NC}   ${NC}[${GREEN}03${NC}]${YELL} Check Bandwith${NC}"
echo -e " ${NC}   ${NC}[${GREEN}04${NC}]${YELL} Create Slowdns${NC}"
echo -e " ${NC}   ${NC}[${GREEN}05${NC}]${YELL} Clear Cache / Sampah${NC}"
echo -e " ${NC}   ${NC}[${GREEN}06${NC}]${YELL} Fixx Cert Domain SSL${NC}"
echo -e " ${NC}   ${NC}[${GREEN}07${NC}]${YELL} Check Info Port VPN${NC}"
echo -e " ${NC}   ${NC}[${GREEN}08${NC}]${YELL} SpeedTest${NC}"
echo -e " ${NC}   ${NC}[${RED}0X${NC}]${RED} Back To Menu${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e ""
read -p "  Select From Options [ 1-8 / 0X ] »» " menu

case $menu in
1)  clear ;
    nano /etc/kyt.txt
    ;;
2) clear ;
    addhost
    ;;
3) clear ;
    bw
    ;;
4) clear ;
    sd
    ;;
5) clear ;
    clearcache
    ;;
6) clear ;
    fixcert
;;
7) clear ;
    prot
;;
8) clear ;
   speedtest
;;
0 | 00 | x | X | 0x | 0X) clear ;
    menu
;;
*)
    m-system
    ;;
esac