#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Tøxic 
# Email      » johntezali56@gmail.com
# telegram   » https://t.me/ToxicSavage
# whatsapp   » wa.me/+254716637803
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Toxic Savage

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'
BGWHITE='\e[0;100;37m'

clear

echo -e ""
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}  ${BGWHITE}               MENU MANAGER TRIAL               ${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " ${NC} ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " ${NC}   ${NC}[${GREEN}01${NC}]${YELL} Trial Account SSH & OVPN${NC}"
echo -e " ${NC}   ${NC}[${GREEN}02${NC}]${YELL} Trial Account XRAY SS WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}03${NC}]${YELL} Trial Account XRAY TR WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}04${NC}]${YELL} Trial Account XRAY VLESS WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${GREEN}05${NC}]${YELL} Trial Account XRAY VMESS WS/GRPC${NC}"
echo -e " ${NC}   ${NC}[${RED}0X${NC}]${RED} ComeBack Menu${NC}"
echo -e " ${NC} ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e ""
read -p "  Select From Options [ 1-5 / 0X ] »» " menu

case $menu in
1 | 01) clear ;
    trial
    ;;
2 | 02) clear ;
    trialss
    ;;
3 | 03) clear ;
    trialtr
    ;;
4 | 04) clear ;
    trialvless
    ;;
5 | 05) clear ;
    trialws
    ;;
0 | 00 | x | X | 0x | 0X)
    clear
    menu
    ;;      
*)
    m-trial
    ;;
esac